name: TntRunCore
version: '${project.version}'
main: com.goottsy.TntRunCore
api-version: '1.19'
authors: [ Goottsy ]
description: Un plugin con muchas cosas de ...
website: https://twitter.com/Goottsy